# Generated by Django 2.1.7 on 2019-03-14 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='steps',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipe'),
        ),
        migrations.AddField(
            model_name='step',
            name='recipe',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipe'),
        ),
    ]
